curl -X 'POST' \
  'http://localhost:8080/showProducts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"warehouse_id": 1}'

curl -X 'POST' \
  'http://localhost:8080/showProducts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"warehouse_id": 2}'

curl -X 'POST' \
  'http://localhost:8080/showProducts' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"warehouse_id": 3}'