### Запрос на получение вещей на 1 складе
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.GetProductsByWarehouse",
  "params": [{"warehouse_id": 1}],
  "id": "coola"
}

### Запрос на получение вещей на 2 складе
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.GetProductsByWarehouse",
  "params": [{"warehouse_id": 2}],
  "id": "coola"
}

### Запрос на получение вещей на 3 складе
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.GetProductsByWarehouse",
  "params": [{"warehouse_id": 3}],
  "id": "coola"
}