  curl -X 'POST' \
  'http://localhost:8080/rpc' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "method": "ProductService.GetProductsByWarehouse",
    "params": [{"warehouse_id": 1}],
    "id": "coola"
    }'

  curl -X 'POST' \
  'http://localhost:8080/rpc' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "method": "ProductService.GetProductsByWarehouse",
    "params": [{"warehouse_id": 2}],
    "id": "coola"
    }'


  curl -X 'POST' \
  'http://localhost:8080/rpc' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "method": "ProductService.GetProductsByWarehouse",
    "params": [{"warehouse_id": 3}],
    "id": "coola"
    }'
