### Запрос на возврат 2 вещей по заказу 422ab5fa-fbf1-461a-99dc-2c6a49c323f1
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.ReleaseProducts",
  "params": [{"products":[{"reservation_id":"422ab5fa-fbf1-461a-99dc-2c6a49c323f1","code": "12345", "quantity": 2}]}],
  "id": "coola"
}

### Запрос на возврат 2 заказов по 2 вещи в каждом
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.ReleaseProducts",
  "params": [{"products":
  [
    {"reservation_id":"422ab5fa-fbf1-461a-99dc-2c6a49c323f1","code": "12345", "quantity": 2},
    {"reservation_id":"965ac486-0451-4e87-be55-2f985cdbf292","code": "12346", "quantity": 2}
  ]
  }],
  "id": "coola"
}
