### Запрос на резервацию 5 продуктов 
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.ReserveProducts",
  "params": [{"products":[{"code": "12345", "quantity": 5}]}],
  "id": "coola"
}

### Запрос на резервацию 8 продуктов 
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.ReserveProducts",
  "params": [{"products":[{"code": "12345", "quantity": 8}]}],
  "id": "coola"
}

### Запрос на резервацию 5 и 4 продуктов разных кодов
POST /rpc HTTP/1.1
Host: localhost:8080
accept: application/json
Content-Type: application/json

{
  "method": "ProductService.ReserveProducts",
  "params": [{"products":[{"code": "12345", "quantity": 5}, {"code": "12346", "quantity": 4}]}],
  "id": "coola"
}
